/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

/**
 *
 * @author Leandro Montero L
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Window_Consultas
     */
    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_Volver = new javax.swing.JButton();
        labelTiempoPromedio = new javax.swing.JLabel();
        labelHoraDelDiaEstacionamientosMasLlenos = new javax.swing.JLabel();
        labelCualEstacionamientoSeLlenaMas = new javax.swing.JLabel();
        label10ConductoresConMasVisitas = new javax.swing.JLabel();
        label5ConductoresConMasTiempoEnElEstacionamiento = new javax.swing.JLabel();
        labelMostrarPorEstacionamientoLos3EspaciosPreferidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Boton_Volver.setText("Volver");
        Boton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VolverActionPerformed(evt);
            }
        });

        labelTiempoPromedio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelTiempoPromedio.setForeground(new java.awt.Color(0, 0, 255));
        labelTiempoPromedio.setText("» Tiempo promedio de la permanencia por vehículo dentro de la organización.");
        labelTiempoPromedio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelHoraDelDiaEstacionamientosMasLlenos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelHoraDelDiaEstacionamientosMasLlenos.setForeground(new java.awt.Color(0, 0, 255));
        labelHoraDelDiaEstacionamientosMasLlenos.setText("» Hora del día en los estacionamientos están más llenos.");
        labelHoraDelDiaEstacionamientosMasLlenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelCualEstacionamientoSeLlenaMas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelCualEstacionamientoSeLlenaMas.setForeground(new java.awt.Color(0, 0, 255));
        labelCualEstacionamientoSeLlenaMas.setText("» Cuál estacionamiento tiende a llenarse más rápido.");
        labelCualEstacionamientoSeLlenaMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label10ConductoresConMasVisitas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label10ConductoresConMasVisitas.setForeground(new java.awt.Color(0, 0, 255));
        label10ConductoresConMasVisitas.setText("» Los 10 conductores con más visitas al estacionamiento.");
        label10ConductoresConMasVisitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        label5ConductoresConMasTiempoEnElEstacionamiento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label5ConductoresConMasTiempoEnElEstacionamiento.setForeground(new java.awt.Color(0, 0, 255));
        label5ConductoresConMasTiempoEnElEstacionamiento.setText("» Los 5 conductores con más tiempo de vehículo dentro del estacionamiento.");
        label5ConductoresConMasTiempoEnElEstacionamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelMostrarPorEstacionamientoLos3EspaciosPreferidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMostrarPorEstacionamientoLos3EspaciosPreferidos.setForeground(new java.awt.Color(0, 0, 255));
        labelMostrarPorEstacionamientoLos3EspaciosPreferidos.setText("» Mostrar por estacionamiento los 3 números preferidos por los usuarios");
        labelMostrarPorEstacionamientoLos3EspaciosPreferidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Boton_Volver))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTiempoPromedio)
                    .addComponent(labelHoraDelDiaEstacionamientosMasLlenos)
                    .addComponent(labelCualEstacionamientoSeLlenaMas)
                    .addComponent(label10ConductoresConMasVisitas)
                    .addComponent(label5ConductoresConMasTiempoEnElEstacionamiento)
                    .addComponent(labelMostrarPorEstacionamientoLos3EspaciosPreferidos))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTiempoPromedio)
                .addGap(18, 18, 18)
                .addComponent(labelHoraDelDiaEstacionamientosMasLlenos)
                .addGap(18, 18, 18)
                .addComponent(labelCualEstacionamientoSeLlenaMas)
                .addGap(18, 18, 18)
                .addComponent(label10ConductoresConMasVisitas)
                .addGap(18, 18, 18)
                .addComponent(label5ConductoresConMasTiempoEnElEstacionamiento)
                .addGap(18, 18, 18)
                .addComponent(labelMostrarPorEstacionamientoLos3EspaciosPreferidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(Boton_Volver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VolverActionPerformed
        Principal vp= new Principal();
        vp.setVisible(true);
        dispose();
    }//GEN-LAST:event_Boton_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Volver;
    private javax.swing.JLabel label10ConductoresConMasVisitas;
    private javax.swing.JLabel label5ConductoresConMasTiempoEnElEstacionamiento;
    private javax.swing.JLabel labelCualEstacionamientoSeLlenaMas;
    private javax.swing.JLabel labelHoraDelDiaEstacionamientosMasLlenos;
    private javax.swing.JLabel labelMostrarPorEstacionamientoLos3EspaciosPreferidos;
    private javax.swing.JLabel labelTiempoPromedio;
    // End of variables declaration//GEN-END:variables
}
