/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.awt.Color;
import javax.swing.JOptionPane;
import models.Estacionamiento;
import models.ListaConductores;
import models.ListaEstacionamientos;
import main.Main.*;

/**
 *
 * @author Leandro Montero
 */
public class Espacios extends javax.swing.JFrame {
        
    /**
     * Creates new form Window_Espacios
     */
    
    public Espacios() {
        
        
        
        
        
        

        
        
        initComponents();
        Nombre_Conductor.setText("Conductor: "+main.Main.conductoractual.getNombre());
  
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Boton_Actualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Boton_Espacio1 = new javax.swing.JButton();
        Boton_Espacio2 = new javax.swing.JButton();
        Boton_Espacio3 = new javax.swing.JButton();
        Boton_Espacio4 = new javax.swing.JButton();
        Boton_Espacio5 = new javax.swing.JButton();
        Boton_Espacio6 = new javax.swing.JButton();
        Boton_Espacio7 = new javax.swing.JButton();
        Boton_Espacio8 = new javax.swing.JButton();
        Boton_Espacio9 = new javax.swing.JButton();
        Boton_Espacio10 = new javax.swing.JButton();
        Boton_Espacio11 = new javax.swing.JButton();
        Boton_Espacio12 = new javax.swing.JButton();
        Boton_Espacio13 = new javax.swing.JButton();
        Boton_Espacio14 = new javax.swing.JButton();
        Boton_Espacio15 = new javax.swing.JButton();
        Boton_Espacio16 = new javax.swing.JButton();
        Boton_Espacio17 = new javax.swing.JButton();
        Boton_Espacio18 = new javax.swing.JButton();
        Boton_Espacio19 = new javax.swing.JButton();
        Boton_Espacio20 = new javax.swing.JButton();
        Boton_Espacio21 = new javax.swing.JButton();
        Boton_Espacio22 = new javax.swing.JButton();
        Boton_Espacio23 = new javax.swing.JButton();
        Boton_Espacio24 = new javax.swing.JButton();
        Boton_Espacio25 = new javax.swing.JButton();
        ComboBox_Estacionamientos = new javax.swing.JComboBox();
        Nombre_Conductor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel3.setText("Espacios Actuales del Estacionamiento");

        Boton_Actualizar.setText("Actualizar");
        Boton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ActualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 10)); // NOI18N
        jLabel4.setText("Presione \"Actualizar\" para ver los espacios disponibles");

        Boton_Espacio1.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio1.setText("E1");
        Boton_Espacio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio1ActionPerformed(evt);
            }
        });

        Boton_Espacio2.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio2.setText("E2");
        Boton_Espacio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio2ActionPerformed(evt);
            }
        });

        Boton_Espacio3.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio3.setText("E3");

        Boton_Espacio4.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio4.setText("E4");

        Boton_Espacio5.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio5.setText("E5");

        Boton_Espacio6.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio6.setText("E6");
        Boton_Espacio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio6ActionPerformed(evt);
            }
        });

        Boton_Espacio7.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio7.setText("E7");
        Boton_Espacio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio7ActionPerformed(evt);
            }
        });

        Boton_Espacio8.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio8.setText("E8");
        Boton_Espacio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio8ActionPerformed(evt);
            }
        });

        Boton_Espacio9.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio9.setText("E9");
        Boton_Espacio9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio9ActionPerformed(evt);
            }
        });

        Boton_Espacio10.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio10.setText("E10");
        Boton_Espacio10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio10ActionPerformed(evt);
            }
        });

        Boton_Espacio11.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio11.setText("E11");
        Boton_Espacio11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio11ActionPerformed(evt);
            }
        });

        Boton_Espacio12.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio12.setText("E12");
        Boton_Espacio12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio12ActionPerformed(evt);
            }
        });

        Boton_Espacio13.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio13.setText("E13");
        Boton_Espacio13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio13ActionPerformed(evt);
            }
        });

        Boton_Espacio14.setBackground(new java.awt.Color(0, 0, 204));
        Boton_Espacio14.setText("E14");
        Boton_Espacio14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio14ActionPerformed(evt);
            }
        });

        Boton_Espacio15.setBackground(new java.awt.Color(0, 51, 204));
        Boton_Espacio15.setText("E15");
        Boton_Espacio15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio15ActionPerformed(evt);
            }
        });

        Boton_Espacio16.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio16.setText("E16");
        Boton_Espacio16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio16ActionPerformed(evt);
            }
        });

        Boton_Espacio17.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio17.setText("E17");
        Boton_Espacio17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio17ActionPerformed(evt);
            }
        });

        Boton_Espacio18.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio18.setText("E18");
        Boton_Espacio18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio18ActionPerformed(evt);
            }
        });

        Boton_Espacio19.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio19.setText("E19");
        Boton_Espacio19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio19ActionPerformed(evt);
            }
        });

        Boton_Espacio20.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio20.setText("E20");
        Boton_Espacio20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio20ActionPerformed(evt);
            }
        });

        Boton_Espacio21.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio21.setText("E21");
        Boton_Espacio21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio21ActionPerformed(evt);
            }
        });

        Boton_Espacio22.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio22.setText("E22");
        Boton_Espacio22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio22ActionPerformed(evt);
            }
        });

        Boton_Espacio23.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio23.setText("E23");
        Boton_Espacio23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio23ActionPerformed(evt);
            }
        });

        Boton_Espacio24.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio24.setText("E24");
        Boton_Espacio24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio24ActionPerformed(evt);
            }
        });

        Boton_Espacio25.setBackground(new java.awt.Color(51, 255, 0));
        Boton_Espacio25.setText("E25");
        Boton_Espacio25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Espacio25ActionPerformed(evt);
            }
        });

        Nombre_Conductor.setText("Conductor: ...");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/images/dmeu_pcalm_9_ble_1_std.lang.all.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Boton_Espacio1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton_Espacio2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton_Espacio3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Boton_Espacio4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton_Espacio5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton_Espacio6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton_Espacio7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Boton_Espacio8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Boton_Espacio9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Boton_Espacio10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Boton_Espacio22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Boton_Espacio23, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Boton_Espacio21, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Boton_Espacio24, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Boton_Espacio25, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Boton_Espacio20, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Boton_Espacio19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Boton_Espacio18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(Boton_Espacio17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Boton_Espacio16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(32, 32, 32)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(65, 65, 65)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Boton_Espacio12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Boton_Espacio11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Boton_Espacio13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Boton_Espacio15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Boton_Espacio14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Nombre_Conductor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Boton_Actualizar)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ComboBox_Estacionamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(509, 509, 509))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBox_Estacionamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_Actualizar)
                            .addComponent(Nombre_Conductor))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Espacio1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Espacio2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Espacio3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Espacio4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Espacio5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Espacio6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Espacio7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Espacio8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Espacio9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Espacio10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Boton_Espacio25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton_Espacio24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton_Espacio13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Espacio23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Boton_Espacio11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Boton_Espacio12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton_Espacio16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Espacio17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Espacio18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Espacio19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_Espacio20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Boton_Espacio22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton_Espacio21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Boton_Espacio14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(Boton_Espacio15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ActualizarActionPerformed
        //Boton_Espacio1.setBackground(Color.red);
        //Boton_Espacio1.setBackground(Color.gray);
        //Verificar Estacionamiento
        String EstSeleccionado=ComboBox_Estacionamientos.getSelectedItem().toString();
        System.out.print(EstSeleccionado);
        
        //Verificar Disponibilidad de Espacios en el Estacionamiento
        
        
        
    }//GEN-LAST:event_Boton_ActualizarActionPerformed

    private void Boton_Espacio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio6ActionPerformed

    private void Boton_Espacio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio7ActionPerformed

    private void Boton_Espacio8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio8ActionPerformed

    private void Boton_Espacio9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio9ActionPerformed

    private void Boton_Espacio10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio10ActionPerformed

    private void Boton_Espacio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio2ActionPerformed

    private void Boton_Espacio11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio11ActionPerformed

    private void Boton_Espacio12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio12ActionPerformed

    private void Boton_Espacio13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio13ActionPerformed

    private void Boton_Espacio14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio14ActionPerformed

    private void Boton_Espacio15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio15ActionPerformed

    private void Boton_Espacio16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio16ActionPerformed

    private void Boton_Espacio17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio17ActionPerformed

    private void Boton_Espacio18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio18ActionPerformed

    private void Boton_Espacio19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio19ActionPerformed

    private void Boton_Espacio20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio20ActionPerformed

    private void Boton_Espacio21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio21ActionPerformed

    private void Boton_Espacio22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio22ActionPerformed

    private void Boton_Espacio23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio23ActionPerformed

    private void Boton_Espacio24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio24ActionPerformed

    private void Boton_Espacio25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Espacio25ActionPerformed

    private void Boton_Espacio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Espacio1ActionPerformed
        if(Boton_Espacio1.getBackground()==Color.red){
            JOptionPane.showMessageDialog(null,"Este espacio se encuentra Ocupado");
        }
        if(Boton_Espacio1.getBackground()==Color.yellow){
            JOptionPane.showMessageDialog(null,"Este espacio se encuentra Reservado");
        }
        if(Boton_Espacio1.getBackground()==Color.gray){
            JOptionPane.showMessageDialog(null,"Espacio No Disponible");
        }
        Boton_Espacio1.setBackground(Color.RED);
    }//GEN-LAST:event_Boton_Espacio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Espacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Espacios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Actualizar;
    private javax.swing.JButton Boton_Espacio1;
    private javax.swing.JButton Boton_Espacio10;
    private javax.swing.JButton Boton_Espacio11;
    private javax.swing.JButton Boton_Espacio12;
    private javax.swing.JButton Boton_Espacio13;
    private javax.swing.JButton Boton_Espacio14;
    private javax.swing.JButton Boton_Espacio15;
    private javax.swing.JButton Boton_Espacio16;
    private javax.swing.JButton Boton_Espacio17;
    private javax.swing.JButton Boton_Espacio18;
    private javax.swing.JButton Boton_Espacio19;
    private javax.swing.JButton Boton_Espacio2;
    private javax.swing.JButton Boton_Espacio20;
    private javax.swing.JButton Boton_Espacio21;
    private javax.swing.JButton Boton_Espacio22;
    private javax.swing.JButton Boton_Espacio23;
    private javax.swing.JButton Boton_Espacio24;
    private javax.swing.JButton Boton_Espacio25;
    private javax.swing.JButton Boton_Espacio3;
    private javax.swing.JButton Boton_Espacio4;
    private javax.swing.JButton Boton_Espacio5;
    private javax.swing.JButton Boton_Espacio6;
    private javax.swing.JButton Boton_Espacio7;
    private javax.swing.JButton Boton_Espacio8;
    private javax.swing.JButton Boton_Espacio9;
    private javax.swing.JComboBox ComboBox_Estacionamientos;
    private javax.swing.JLabel Nombre_Conductor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
